#!/usr/bin/env bash
# Vectorize a black-on-white treeline PNG into the landing page SVG asset.
#
# Input: a high-contrast silhouette (solid black trees, pure white sky),
# e.g. generated by nano-banana — see .claude/skills/treeline/SKILL.md for
# the full generation prompt and workflow.
#
# Usage: scripts/vectorize-treeline.sh input.png [output.svg]
#
# Prints the SVG_WIDTH / SVG_HEIGHT / BAND_TOP / BAND_HEIGHT constants that
# must be updated in src/viz/subjects/LandingPageTreeline.ts for the new
# asset.
set -euo pipefail

command -v magick >/dev/null || { echo "imagemagick required (brew install imagemagick)"; exit 1; }
command -v potrace >/dev/null || { echo "potrace required (brew install potrace)"; exit 1; }

in="$1"
out="${2:-$(dirname "$0")/../src/viz/img/landing/treeline.svg}"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

magick "$in" -colorspace Gray -threshold 50% "$tmp/bw.pbm"
potrace "$tmp/bw.pbm" -s -o "$out" --turdsize 10 --alphamax 1.0

read -r width height <<<"$(magick "$in" -format "%w %h" info:)"
# negate (trees become white) and add a black frame so trim only removes
# sky rows — without it, a solid tree base touching the bottom edge would
# be trimmed away as uniform border and under-measure the band
read -r bandHeight bandTop <<<"$(magick "$tmp/bw.pbm" -negate -bordercolor black -border 1 -trim -format "%h %Y" info: | tr -d '+')"
bandTop=$((bandTop - 1))

echo "Wrote $out"
echo
echo "Update src/viz/subjects/LandingPageTreeline.ts:"
echo "  const SVG_WIDTH = $width;"
echo "  const SVG_HEIGHT = $height;"
echo "  const BAND_TOP = $bandTop;"
echo "  const BAND_HEIGHT = $bandHeight;"
